name: Upload Website - Improved 

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
    - uses: actions/checkout@master
    - run: >
        aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET }}/ --acl public-read --follow-symlinks --delete --exclude './git'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
